### ISSUE TITLE
JOSS review

### ISSUE THREAD

**Issue by roryk** [MonashBioinformaticsPlatform/varistran#2]
Hi everyone, I've been looking at varistran for the JOSS review. The diagnostic plots look super useful. 

I fixed a minor issue with the tests in a pull request and wrote up some other issues here:

https://github.com/roryk/varistran-review/blob/master/review.md

It would be nice to have more of an explanation regarding what the stability plot is plotting and what a well stabilized plot would look like. I was expecting the variance to be even across the expression levels but it looks like that plot isn't that.

Thanks!

**Comment by pfh** [comment]
Hi roryk,

Thanks for the thorough review.

I have merged your pull request.

Your understanding of the stability plot is correct. For very small counts, the variability does fall off with the Anscombe transformation. As far as I can tell, this is going to happen with any variance stabilizing transformation on count data. The problem only becomes severe with counts averaging around three or less, and counts this low don't really contain much information.

I will try to fix the issues you've listed in your review in the next few days.

**Comment by pfh** [comment]
> Would be nice if in main description on the github page, the bottomly dataset or one of the other test datasets was shown as setup as a test set. I only discovered some test datasets by looking at the tests.

I've now included code for loading the Bottomly dataset in the README.md.


> NBPSeq isn't mentioned as a dependency anywhere, but is required to run the vst_stability_plots.R test.

I have added packages needed for testing to the suggested dependencies:

* biomaRt
* DESeq2
* NBPSeq


> Would be nice if the plot_heatmap function subset the variable genes so it did not plot the whole thing by default.

I have added a parameter "n" to the plot_heatmap function, to specify the number of rows to show. It will pick the n rows with the largest span of transformed expression levels.


> R CMD check fails

This was surprising, as devtools::check passes. It looks like the correct way to run the check without devtools is:

    R CMD BUILD .
    R CMD CHECK varistran_*.tar.gz

which should run without errors. The build step fills in the missing Author field.

I've now released version v1.0.2, hope it is satisfactory.

**Comment by roryk** [comment]
Awesome! Thanks, that looks great. The JOSS wants two more things.

1) a section regarding how to get support/contribute
2) for software packages/papers/etc referred to to have references (so edgeR, DESeq2, NBPSeq, etc).

After that, looks all set to me. Thanks so much!

**Comment by pfh** [comment]
Ok, I've added to the README.md a "Supporting/contributing" section, and references for packages Varistran uses and for test data.

**Comment by pfh** [comment]
Varistran is now published in the Journal of Open Source Software. http://dx.doi.org/10.21105/joss.00257
